// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

/// import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVWvrhQgIbtTIdbjes84BO563OlL3XnA4',
    appId: '1:601092241016:web:e4c8435245b140fa4fdf8d',
    messagingSenderId: '601092241016',
    projectId: 'projeto-green-home',
    authDomain: 'projeto-green-home.firebaseapp.com',
    storageBucket: 'projeto-green-home.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYDis8z821JURLtAdqATBQBJ6owHXbS4',
    appId: '1:601092241016:android:b940c2c09ea2be974fdf8d',
    messagingSenderId: '601092241016',
    projectId: 'projeto-green-home',
    storageBucket: 'projeto-green-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcVgn-hf5ohWHDjmqbqDcHoWO8BehYmg',
    appId: '1:601092241016:ios:42c945067015a70c4fdf8d',
    messagingSenderId: '601092241016',
    projectId: 'projeto-green-home',
    storageBucket: 'projeto-green-home.firebasestorage.app',
    iosBundleId: 'com.example.appGreenhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbcVgn-hf5ohWHDjmqbqDcHoWO8BehYmg',
    appId: '1:601092241016:ios:42c945067015a70c4fdf8d',
    messagingSenderId: '601092241016',
    projectId: 'projeto-green-home',
    storageBucket: 'projeto-green-home.firebasestorage.app',
    iosBundleId: 'com.example.appGreenhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVWvrhQgIbtTIdbjes84BO563OlL3XnA4',
    appId: '1:601092241016:web:127d8f73ef1b5b754fdf8d',
    messagingSenderId: '601092241016',
    projectId: 'projeto-green-home',
    authDomain: 'projeto-green-home.firebaseapp.com',
    storageBucket: 'projeto-green-home.firebasestorage.app',
  );
}
